export const STALE_DATA = {
  count: 303,
  next: "https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit=10&offset=10",
  previous: null,
  results: [
    {
      id: "c2a0e237-5fb8-4cca-aadd-c0aefda2c12e",
      url: "https://ll.thespacedevs.com/2.2.0/launch/c2a0e237-5fb8-4cca-aadd-c0aefda2c12e/",
      slug: "kuaizhou-1a-tianmu-1-07-10",
      name: "ABC | Tianmu-1 07-10",
      status: {
        id: 3,
        name: "Launch Successful",
        abbrev: "Success",
        description:
          "The launch vehicle successfully inserted its payload(s) into the target orbit(s).",
      },
      last_updated: "2023-07-20T13:16:29Z",
      net: "2023-07-20T03:20:00Z",
      window_end: "2023-07-20T03:38:00Z",
      window_start: "2023-07-20T03:11:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 194,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/194/",
        name: "ExPace",
        type: "Commercial",
      },
      rocket: {
        id: 7956,
        configuration: {
          id: 135,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/135/",
          name: "Kuaizhou",
          family: "Kuaizhou",
          full_name: "Kuaizhou-1A",
          variant: "1A",
        },
      },
      mission: {
        id: 6473,
        name: "Tianmu-1 07-10",
        description:
          "Small meteorology research satellites using GNSS radio occultation by CASIC subsidiary Xiyong Microelectronics Park.",
        launch_designator: null,
        type: "Earth Science",
        orbit: {
          id: 17,
          name: "Sun-Synchronous Orbit",
          abbrev: "SSO",
        },
      },
      pad: {
        id: 21,
        url: "https://ll.thespacedevs.com/2.2.0/pad/21/",
        agency_id: null,
        name: "Launch Area 95A",
        info_url: null,
        wiki_url:
          "https://en.wikipedia.org/wiki/Jiuquan_Satellite_Launch_Center",
        map_url: "https://www.google.com/maps?q=40.969117,100.343333",
        latitude: "40.969117",
        longitude: "100.343333",
        location: {
          id: 17,
          url: "https://ll.thespacedevs.com/2.2.0/location/17/",
          name: "Jiuquan Satellite Launch Center, People's Republic of China",
          country_code: "CHN",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg",
          timezone_name: "Asia/Shanghai",
          total_launch_count: 199,
          total_landing_count: 0,
        },
        country_code: "CHN",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_21_20200803143253.jpg",
        total_launch_count: 41,
        orbital_launch_attempt_count: 41,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/kuaizhou-1a252_image_20230720042210.jpeg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6464,
      location_launch_attempt_count: 199,
      pad_launch_attempt_count: 41,
      agency_launch_attempt_count: 23,
      orbital_launch_attempt_count_year: 106,
      location_launch_attempt_count_year: 17,
      pad_launch_attempt_count_year: 6,
      agency_launch_attempt_count_year: 3,
    },
    {
      id: "9e94b0b7-d88b-4cdf-9793-acdec5850613",
      url: "https://ll.thespacedevs.com/2.2.0/launch/9e94b0b7-d88b-4cdf-9793-acdec5850613/",
      slug: "falcon-9-block-5-starlink-group-6-15",
      name: "Falcon 9 Block 5 | Starlink Group 6-15",
      status: {
        id: 3,
        name: "Launch Successful",
        abbrev: "Success",
        description:
          "The launch vehicle successfully inserted its payload(s) into the target orbit(s).",
      },
      last_updated: "2023-07-20T04:56:15Z",
      net: "2023-07-20T04:09:30Z",
      window_end: "2023-07-20T04:09:30Z",
      window_start: "2023-07-20T04:09:30Z",
      net_precision: {
        id: 0,
        name: "Second",
        abbrev: "SEC",
        description: "The T-0 is accurate to the second.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 121,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
        name: "SpaceX",
        type: "Commercial",
      },
      rocket: {
        id: 7873,
        configuration: {
          id: 164,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/164/",
          name: "Falcon 9",
          family: "Falcon",
          full_name: "Falcon 9 Block 5",
          variant: "Block 5",
        },
      },
      mission: {
        id: 6381,
        name: "Starlink Group 6-15",
        description:
          "A batch of satellites for the Starlink mega-constellation - SpaceX's project for space-based Internet communication system.",
        launch_designator: null,
        type: "Communications",
        orbit: {
          id: 8,
          name: "Low Earth Orbit",
          abbrev: "LEO",
        },
      },
      pad: {
        id: 16,
        url: "https://ll.thespacedevs.com/2.2.0/pad/16/",
        agency_id: null,
        name: "Space Launch Complex 4E",
        info_url: null,
        wiki_url: "",
        map_url: "https://www.google.com/maps?q=34.632,-120.611",
        latitude: "34.632",
        longitude: "-120.611",
        location: {
          id: 11,
          url: "https://ll.thespacedevs.com/2.2.0/location/11/",
          name: "Vandenberg SFB, CA, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_11_20200803142416.jpg",
          timezone_name: "America/Los_Angeles",
          total_launch_count: 724,
          total_landing_count: 11,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_16_20200803143532.jpg",
        total_launch_count: 115,
        orbital_launch_attempt_count: 115,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20230522092512.png",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6465,
      location_launch_attempt_count: 724,
      pad_launch_attempt_count: 115,
      agency_launch_attempt_count: 262,
      orbital_launch_attempt_count_year: 107,
      location_launch_attempt_count_year: 15,
      pad_launch_attempt_count_year: 15,
      agency_launch_attempt_count_year: 49,
    },
    {
      id: "160d6bd1-4ac6-43bd-8284-12e457cde9d7",
      url: "https://ll.thespacedevs.com/2.2.0/launch/160d6bd1-4ac6-43bd-8284-12e457cde9d7/",
      slug: "ceres-1-unknown-payload",
      name: "Ceres-1 | Unknown Payload",
      status: {
        id: 1,
        name: "Go for Launch",
        abbrev: "Go",
        description: "Current T-0 confirmed by official or reliable sources.",
      },
      last_updated: "2023-07-20T04:37:11Z",
      net: "2023-07-22T05:15:00Z",
      window_end: "2023-07-22T06:06:00Z",
      window_start: "2023-07-22T05:00:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 1021,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/1021/",
        name: "Galactic Energy",
        type: "Commercial",
      },
      rocket: {
        id: 7958,
        configuration: {
          id: 461,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/461/",
          name: "Ceres-1",
          family: "Ceres-1",
          full_name: "Ceres-1",
          variant: "Ceres-1",
        },
      },
      mission: null,
      pad: {
        id: 21,
        url: "https://ll.thespacedevs.com/2.2.0/pad/21/",
        agency_id: null,
        name: "Launch Area 95A",
        info_url: null,
        wiki_url:
          "https://en.wikipedia.org/wiki/Jiuquan_Satellite_Launch_Center",
        map_url: "https://www.google.com/maps?q=40.969117,100.343333",
        latitude: "40.969117",
        longitude: "100.343333",
        location: {
          id: 17,
          url: "https://ll.thespacedevs.com/2.2.0/location/17/",
          name: "Jiuquan Satellite Launch Center, People's Republic of China",
          country_code: "CHN",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg",
          timezone_name: "Asia/Shanghai",
          total_launch_count: 199,
          total_landing_count: 0,
        },
        country_code: "CHN",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_21_20200803143253.jpg",
        total_launch_count: 41,
        orbital_launch_attempt_count: 41,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/ceres-1_image_20201106095300.jpeg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6466,
      location_launch_attempt_count: 200,
      pad_launch_attempt_count: 42,
      agency_launch_attempt_count: 6,
      orbital_launch_attempt_count_year: 6466,
      location_launch_attempt_count_year: 18,
      pad_launch_attempt_count_year: 7,
      agency_launch_attempt_count_year: 2,
    },
    {
      id: "c407b340-49e6-447a-b872-8441618f0ec7",
      url: "https://ll.thespacedevs.com/2.2.0/launch/c407b340-49e6-447a-b872-8441618f0ec7/",
      slug: "falcon-9-block-5-starlink-group-6-6",
      name: "Falcon 9 Block 5 | Starlink Group 6-6",
      status: {
        id: 8,
        name: "To Be Confirmed",
        abbrev: "TBC",
        description:
          "Awaiting official confirmation - current date is known with some certainty.",
      },
      last_updated: "2023-07-19T14:02:40Z",
      net: "2023-07-22T23:31:00Z",
      window_end: "2023-07-23T03:35:00Z",
      window_start: "2023-07-22T23:01:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: 35,
      weather_concerns:
        "Cumulus Cloud Rule, Anvil Cloud Rules, Surface Electric Fields Rule",
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 121,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
        name: "SpaceX",
        type: "Commercial",
      },
      rocket: {
        id: 7845,
        configuration: {
          id: 164,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/164/",
          name: "Falcon 9",
          family: "Falcon",
          full_name: "Falcon 9 Block 5",
          variant: "Block 5",
        },
      },
      mission: {
        id: 6352,
        name: "Starlink Group 6-6",
        description:
          "A batch of satellites for the Starlink mega-constellation - SpaceX's project for space-based Internet communication system.",
        launch_designator: null,
        type: "Communications",
        orbit: {
          id: 8,
          name: "Low Earth Orbit",
          abbrev: "LEO",
        },
      },
      pad: {
        id: 80,
        url: "https://ll.thespacedevs.com/2.2.0/pad/80/",
        agency_id: 121,
        name: "Space Launch Complex 40",
        info_url: null,
        wiki_url:
          "https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_40",
        map_url: "https://www.google.com/maps?q=28.56194122,-80.57735736",
        latitude: "28.56194122",
        longitude: "-80.57735736",
        location: {
          id: 12,
          url: "https://ll.thespacedevs.com/2.2.0/location/12/",
          name: "Cape Canaveral, FL, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg",
          timezone_name: "America/New_York",
          total_launch_count: 896,
          total_landing_count: 34,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_80_20200803143323.jpg",
        total_launch_count: 189,
        orbital_launch_attempt_count: 189,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20230503090151.png",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6467,
      location_launch_attempt_count: 897,
      pad_launch_attempt_count: 190,
      agency_launch_attempt_count: 263,
      orbital_launch_attempt_count_year: 109,
      location_launch_attempt_count_year: 29,
      pad_launch_attempt_count_year: 27,
      agency_launch_attempt_count_year: 50,
    },
    {
      id: "22a6f1ed-afcd-455d-9316-5aaf8f39e864",
      url: "https://ll.thespacedevs.com/2.2.0/launch/22a6f1ed-afcd-455d-9316-5aaf8f39e864/",
      slug: "long-march-2d-unknown-payload",
      name: "Long March 2D | Unknown Payload",
      status: {
        id: 1,
        name: "Go for Launch",
        abbrev: "Go",
        description: "Current T-0 confirmed by official or reliable sources.",
      },
      last_updated: "2023-07-18T17:10:33Z",
      net: "2023-07-23T03:00:00Z",
      window_end: "2023-07-23T03:20:00Z",
      window_start: "2023-07-23T02:41:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 88,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/88/",
        name: "China Aerospace Science and Technology Corporation",
        type: "Government",
      },
      rocket: {
        id: 7957,
        configuration: {
          id: 17,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/17/",
          name: "Long March 2D",
          family: "Long March 2",
          full_name: "Long March 2D",
          variant: "2D",
        },
      },
      mission: null,
      pad: {
        id: 25,
        url: "https://ll.thespacedevs.com/2.2.0/pad/25/",
        agency_id: null,
        name: "Launch Complex 9",
        info_url: null,
        wiki_url: "",
        map_url: "https://www.google.com/maps?q=38.849,111.608",
        latitude: "38.849",
        longitude: "111.608",
        location: {
          id: 19,
          url: "https://ll.thespacedevs.com/2.2.0/location/19/",
          name: "Taiyuan Satellite Launch Center, People's Republic of China",
          country_code: "CHN",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_19_20200803142421.jpg",
          timezone_name: "Asia/Shanghai",
          total_launch_count: 122,
          total_landing_count: 0,
        },
        country_code: "CHN",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_25_20200803143501.jpg",
        total_launch_count: 70,
        orbital_launch_attempt_count: 70,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/long2520march25202d_image_20190222031211.jpeg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6468,
      location_launch_attempt_count: 123,
      pad_launch_attempt_count: 71,
      agency_launch_attempt_count: 428,
      orbital_launch_attempt_count_year: 6468,
      location_launch_attempt_count_year: 6,
      pad_launch_attempt_count_year: 5,
      agency_launch_attempt_count_year: 21,
    },
    {
      id: "af626de1-88f7-418b-8801-a4e897f067a4",
      url: "https://ll.thespacedevs.com/2.2.0/launch/af626de1-88f7-418b-8801-a4e897f067a4/",
      slug: "pslv-ca-ds-sar",
      name: "PSLV-CA | DS-SAR",
      status: {
        id: 8,
        name: "To Be Confirmed",
        abbrev: "TBC",
        description:
          "Awaiting official confirmation - current date is known with some certainty.",
      },
      last_updated: "2023-07-20T05:45:43Z",
      net: "2023-07-26T01:00:00Z",
      window_end: "2023-07-26T04:15:00Z",
      window_start: "2023-07-26T00:15:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 31,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/31/",
        name: "Indian Space Research Organization",
        type: "Government",
      },
      rocket: {
        id: 7908,
        configuration: {
          id: 43,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/43/",
          name: "PSLV",
          family: "PSLV",
          full_name: "PSLV-CA",
          variant: "CA",
        },
      },
      mission: {
        id: 6415,
        name: "DS-SAR",
        description:
          "DS-SAR is a Singaporean Synthetic Aperture Radar (SAR) Earth Observation satellite built by Israel Aerospace Industries (IAI), to be used by both the Singaporean government DSTA (Defence Science and Technology Agency) and commercially operated by ST Electronics.",
        launch_designator: null,
        type: "Earth Science",
        orbit: {
          id: 8,
          name: "Low Earth Orbit",
          abbrev: "LEO",
        },
      },
      pad: {
        id: 50,
        url: "https://ll.thespacedevs.com/2.2.0/pad/50/",
        agency_id: 31,
        name: "Satish Dhawan Space Centre First Launch Pad",
        info_url: null,
        wiki_url:
          "https://en.wikipedia.org/wiki/Satish_Dhawan_Space_Centre_First_Launch_Pad",
        map_url: "https://www.google.com/maps?q=13.733,80.235",
        latitude: "13.733",
        longitude: "80.235",
        location: {
          id: 14,
          url: "https://ll.thespacedevs.com/2.2.0/location/14/",
          name: "Satish Dhawan Space Centre, India",
          country_code: "IND",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_14_20200803142403.jpg",
          timezone_name: "Asia/Kolkata",
          total_launch_count: 89,
          total_landing_count: 0,
        },
        country_code: "IND",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_50_20200803143457.jpg",
        total_launch_count: 55,
        orbital_launch_attempt_count: 55,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/pslv_image_20190520163034.jpg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6469,
      location_launch_attempt_count: 90,
      pad_launch_attempt_count: 56,
      agency_launch_attempt_count: 86,
      orbital_launch_attempt_count_year: 111,
      location_launch_attempt_count_year: 6,
      pad_launch_attempt_count_year: 3,
      agency_launch_attempt_count_year: 6,
    },
    {
      id: "72491a20-315d-4aea-b6df-d1202930bd60",
      url: "https://ll.thespacedevs.com/2.2.0/launch/72491a20-315d-4aea-b6df-d1202930bd60/",
      slug: "falcon-heavy-echostar-24jupiter-3",
      name: "Falcon Heavy | EchoStar 24/Jupiter-3",
      status: {
        id: 8,
        name: "To Be Confirmed",
        abbrev: "TBC",
        description:
          "Awaiting official confirmation - current date is known with some certainty.",
      },
      last_updated: "2023-07-20T07:30:17Z",
      net: "2023-07-27T03:04:00Z",
      window_end: "2023-07-27T05:12:00Z",
      window_start: "2023-07-27T02:04:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 121,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
        name: "SpaceX",
        type: "Commercial",
      },
      rocket: {
        id: 7576,
        configuration: {
          id: 161,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/161/",
          name: "Falcon Heavy",
          family: "Falcon",
          full_name: "Falcon Heavy",
          variant: "Heavy",
        },
      },
      mission: {
        id: 6019,
        name: "EchoStar 24/Jupiter-3",
        description:
          "Geostationary communications satellite built by Maxar Technologies for EchoStar. With a capacity of 500 Gbps, its purpose is to relieve broadband capacity constraints in the Americas.",
        launch_designator: null,
        type: "Communications",
        orbit: {
          id: 2,
          name: "Geostationary Transfer Orbit",
          abbrev: "GTO",
        },
      },
      pad: {
        id: 87,
        url: "https://ll.thespacedevs.com/2.2.0/pad/87/",
        agency_id: 121,
        name: "Launch Complex 39A",
        info_url: null,
        wiki_url:
          "https://en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39#Launch_Pad_39A",
        map_url: "https://www.google.com/maps?q=28.60822681,-80.60428186",
        latitude: "28.60822681",
        longitude: "-80.60428186",
        location: {
          id: 27,
          url: "https://ll.thespacedevs.com/2.2.0/location/27/",
          name: "Kennedy Space Center, FL, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_27_20200803142447.jpg",
          timezone_name: "America/New_York",
          total_launch_count: 220,
          total_landing_count: 0,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_87_20200803143537.jpg",
        total_launch_count: 162,
        orbital_launch_attempt_count: 161,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_heavy_image_20220129192819.jpeg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6470,
      location_launch_attempt_count: 221,
      pad_launch_attempt_count: 163,
      agency_launch_attempt_count: 264,
      orbital_launch_attempt_count_year: 112,
      location_launch_attempt_count_year: 8,
      pad_launch_attempt_count_year: 8,
      agency_launch_attempt_count_year: 51,
    },
    {
      id: "9248a1d0-393f-469a-b9c6-19470247e6fd",
      url: "https://ll.thespacedevs.com/2.2.0/launch/9248a1d0-393f-469a-b9c6-19470247e6fd/",
      slug: "falcon-9-block-5-sda-tranche-0b",
      name: "Falcon 9 Block 5 | SDA Tranche 0B",
      status: {
        id: 2,
        name: "To Be Determined",
        abbrev: "TBD",
        description:
          "Current date is a placeholder or rough estimation based on unreliable or interpreted sources.",
      },
      last_updated: "2023-06-19T18:23:46Z",
      net: "2023-07-31T00:00:00Z",
      window_end: "2023-07-31T00:00:00Z",
      window_start: "2023-07-31T00:00:00Z",
      net_precision: {
        id: 7,
        name: "Month",
        abbrev: "M",
        description: "The T-0 is expected in the given month.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 121,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
        name: "SpaceX",
        type: "Commercial",
      },
      rocket: {
        id: 7730,
        configuration: {
          id: 164,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/164/",
          name: "Falcon 9",
          family: "Falcon",
          full_name: "Falcon 9 Block 5",
          variant: "Block 5",
        },
      },
      mission: {
        id: 6247,
        name: "SDA Tranche 0B",
        description:
          "Second mission launched by the Space Development Agency for the Tranche 0 Transport Layer.",
        launch_designator: null,
        type: "Government/Top Secret",
        orbit: {
          id: 13,
          name: "Polar Orbit",
          abbrev: "PO",
        },
      },
      pad: {
        id: 16,
        url: "https://ll.thespacedevs.com/2.2.0/pad/16/",
        agency_id: null,
        name: "Space Launch Complex 4E",
        info_url: null,
        wiki_url: "",
        map_url: "https://www.google.com/maps?q=34.632,-120.611",
        latitude: "34.632",
        longitude: "-120.611",
        location: {
          id: 11,
          url: "https://ll.thespacedevs.com/2.2.0/location/11/",
          name: "Vandenberg SFB, CA, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_11_20200803142416.jpg",
          timezone_name: "America/Los_Angeles",
          total_launch_count: 724,
          total_landing_count: 11,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_16_20200803143532.jpg",
        total_launch_count: 115,
        orbital_launch_attempt_count: 115,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6472,
      location_launch_attempt_count: 726,
      pad_launch_attempt_count: 116,
      agency_launch_attempt_count: 265,
      orbital_launch_attempt_count_year: 114,
      location_launch_attempt_count_year: 17,
      pad_launch_attempt_count_year: 16,
      agency_launch_attempt_count_year: 52,
    },
    {
      id: "b8f2e028-285c-457d-b807-a6749cfc3af6",
      url: "https://ll.thespacedevs.com/2.2.0/launch/b8f2e028-285c-457d-b807-a6749cfc3af6/",
      slug: "firefly-alpha-flta003-victus-nox",
      name: "Firefly Alpha | FLTA003 (VICTUS NOX)",
      status: {
        id: 2,
        name: "To Be Determined",
        abbrev: "TBD",
        description:
          "Current date is a placeholder or rough estimation based on unreliable or interpreted sources.",
      },
      last_updated: "2023-06-29T06:05:33Z",
      net: "2023-07-31T00:00:00Z",
      window_end: "2023-07-31T00:00:00Z",
      window_start: "2023-07-31T00:00:00Z",
      net_precision: {
        id: 7,
        name: "Month",
        abbrev: "M",
        description: "The T-0 is expected in the given month.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 265,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/265/",
        name: "Firefly Aerospace",
        type: "Commercial",
      },
      rocket: {
        id: 7758,
        configuration: {
          id: 179,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/179/",
          name: "Firefly Alpha",
          family: "Firefly Alpha",
          full_name: "Firefly Alpha",
          variant: "",
        },
      },
      mission: {
        id: 6274,
        name: "FLTA003 (VICTUS NOX)",
        description:
          "Third flight of the Firefly Alpha small sat launcher, carrying a payload for the US Department of Defense.",
        launch_designator: null,
        type: "Government/Top Secret",
        orbit: {
          id: 8,
          name: "Low Earth Orbit",
          abbrev: "LEO",
        },
      },
      pad: {
        id: 39,
        url: "https://ll.thespacedevs.com/2.2.0/pad/39/",
        agency_id: null,
        name: "Space Launch Complex 2W",
        info_url: null,
        wiki_url: "",
        map_url: "https://www.google.com/maps?q=34.7556,-120.6224",
        latitude: "34.7556",
        longitude: "-120.6224",
        location: {
          id: 11,
          url: "https://ll.thespacedevs.com/2.2.0/location/11/",
          name: "Vandenberg SFB, CA, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_11_20200803142416.jpg",
          timezone_name: "America/Los_Angeles",
          total_launch_count: 724,
          total_landing_count: 11,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_39_20200803143542.jpg",
        total_launch_count: 94,
        orbital_launch_attempt_count: 94,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/firefly_alpha_image_20210429094607.jpg",
      infographic: null,
      program: [],
      orbital_launch_attempt_count: 6472,
      location_launch_attempt_count: 726,
      pad_launch_attempt_count: 95,
      agency_launch_attempt_count: 3,
      orbital_launch_attempt_count_year: 114,
      location_launch_attempt_count_year: 17,
      pad_launch_attempt_count_year: 1,
      agency_launch_attempt_count_year: 1,
    },
    {
      id: "7c126e4f-4afd-4c25-bf6f-9017666b56ee",
      url: "https://ll.thespacedevs.com/2.2.0/launch/7c126e4f-4afd-4c25-bf6f-9017666b56ee/",
      slug: "antares-230-cygnus-crs-2-ng-19",
      name: "Antares 230+ | Cygnus CRS-2 NG-19",
      status: {
        id: 1,
        name: "Go for Launch",
        abbrev: "Go",
        description: "Current T-0 confirmed by official or reliable sources.",
      },
      last_updated: "2023-07-19T10:50:44Z",
      net: "2023-08-02T00:31:00Z",
      window_end: "2023-08-02T00:31:00Z",
      window_start: "2023-08-02T00:31:00Z",
      net_precision: {
        id: 1,
        name: "Minute",
        abbrev: "MIN",
        description: "The T-0 is accurate to the minute.",
      },
      probability: null,
      weather_concerns: null,
      holdreason: "",
      failreason: "",
      hashtag: null,
      launch_service_provider: {
        id: 257,
        url: "https://ll.thespacedevs.com/2.2.0/agencies/257/",
        name: "Northrop Grumman Space Systems",
        type: "Commercial",
      },
      rocket: {
        id: 2685,
        configuration: {
          id: 210,
          url: "https://ll.thespacedevs.com/2.2.0/config/launcher/210/",
          name: "Antares 230+",
          family: "Antares",
          full_name: "Antares 230+",
          variant: "230+",
        },
      },
      mission: {
        id: 6004,
        name: "Cygnus CRS-2 NG-19",
        description:
          "This is the 19th flight of the Orbital ATK's uncrewed resupply spacecraft Cygnus and its 18th flight to the International Space Station under the Commercial Resupply Services contract with NASA.",
        launch_designator: null,
        type: "Resupply",
        orbit: {
          id: 8,
          name: "Low Earth Orbit",
          abbrev: "LEO",
        },
      },
      pad: {
        id: 76,
        url: "https://ll.thespacedevs.com/2.2.0/pad/76/",
        agency_id: 44,
        name: "Launch Area 0 A",
        info_url: null,
        wiki_url: "",
        map_url: "https://www.google.com/maps?q=37.8337,-75.4881",
        latitude: "37.8337",
        longitude: "-75.4881",
        location: {
          id: 21,
          url: "https://ll.thespacedevs.com/2.2.0/location/21/",
          name: "Wallops Island, Virginia, USA",
          country_code: "USA",
          map_image:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_21_20200803142423.jpg",
          timezone_name: "America/New_York",
          total_launch_count: 76,
          total_landing_count: 0,
        },
        country_code: "USA",
        map_image:
          "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_76_20200803143538.jpg",
        total_launch_count: 18,
        orbital_launch_attempt_count: 18,
      },
      webcast_live: false,
      image:
        "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/antares2520230252b_image_20191102024633.jpeg",
      infographic: null,
      program: [
        {
          id: 11,
          url: "https://ll.thespacedevs.com/2.2.0/program/11/",
          name: "Commercial Resupply Services",
          description:
            "Commercial Resupply Services (CRS) are a series of flights awarded by NASA for the delivery of cargo and supplies to the International Space Station.The first CRS contracts were signed in 2008 and awarded $1.6 billion to SpaceX for twelve cargo Dragon and $1.9 billion to Orbital Sciences for eight Cygnus flights, covering deliveries to 2016. The Falcon 9 and Antares rockets were also developed under the CRS program to deliver cargo spacecraft to the ISS.",
          agencies: [
            {
              id: 44,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/44/",
              name: "National Aeronautics and Space Administration",
              type: "Government",
            },
            {
              id: 257,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/257/",
              name: "Northrop Grumman Space Systems",
              type: "Commercial",
            },
            {
              id: 1020,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/1020/",
              name: "Sierra Nevada Corporation",
              type: "Commercial",
            },
            {
              id: 121,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/121/",
              name: "SpaceX",
              type: "Commercial",
            },
          ],
          image_url:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/commercial2520_program_20201129212219.png",
          start_date: "2008-12-23T00:00:00Z",
          end_date: null,
          info_url: null,
          wiki_url:
            "https://en.wikipedia.org/wiki/Commercial_Resupply_Services#Commercial_Resupply_Services",
          mission_patches: [],
        },
        {
          id: 17,
          url: "https://ll.thespacedevs.com/2.2.0/program/17/",
          name: "International Space Station",
          description:
            "The International Space Station programme is tied together by a complex set of legal, political and financial agreements between the sixteen nations involved in the project, governing ownership of the various components, rights to crewing and utilization, and responsibilities for crew rotation and resupply of the International Space Station. It was conceived in 1984 by President Ronald Reagan, during the Space Station Freedom project as it was originally called.",
          agencies: [
            {
              id: 16,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/16/",
              name: "Canadian Space Agency",
              type: "Government",
            },
            {
              id: 27,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/27/",
              name: "European Space Agency",
              type: "Multinational",
            },
            {
              id: 37,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/37/",
              name: "Japan Aerospace Exploration Agency",
              type: "Government",
            },
            {
              id: 44,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/44/",
              name: "National Aeronautics and Space Administration",
              type: "Government",
            },
            {
              id: 63,
              url: "https://ll.thespacedevs.com/2.2.0/agencies/63/",
              name: "Russian Federal Space Agency (ROSCOSMOS)",
              type: "Government",
            },
          ],
          image_url:
            "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/international2_program_20201129184745.png",
          start_date: "1998-11-20T06:40:00Z",
          end_date: null,
          info_url:
            "https://www.nasa.gov/mission_pages/station/main/index.html",
          wiki_url:
            "https://en.wikipedia.org/wiki/International_Space_Station_programme",
          mission_patches: [],
        },
      ],
      orbital_launch_attempt_count: 6473,
      location_launch_attempt_count: 77,
      pad_launch_attempt_count: 19,
      agency_launch_attempt_count: 14,
      orbital_launch_attempt_count_year: 115,
      location_launch_attempt_count_year: 4,
      pad_launch_attempt_count_year: 1,
      agency_launch_attempt_count_year: 1,
    },
  ],
};
